// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/libra_res_userinfo.proto

package com.insping.libra.net.proto;

public final class ResUserInfo {
  private ResUserInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserInfoDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.UserInfoData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 uid = 1;</code>
     */
    long getUid();

    /**
     * <code>string sessionKey = 2;</code>
     */
    java.lang.String getSessionKey();
    /**
     * <code>string sessionKey = 2;</code>
     */
    com.google.protobuf.ByteString
        getSessionKeyBytes();

    /**
     * <code>string userAccout = 3;</code>
     */
    java.lang.String getUserAccout();
    /**
     * <code>string userAccout = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserAccoutBytes();

    /**
     * <code>string name = 4;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 4;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string sex = 5;</code>
     */
    java.lang.String getSex();
    /**
     * <code>string sex = 5;</code>
     */
    com.google.protobuf.ByteString
        getSexBytes();

    /**
     * <code>int32 age = 6;</code>
     */
    int getAge();

    /**
     * <code>int32 status = 7;</code>
     */
    int getStatus();

    /**
     * <code>int64 registerTime = 8;</code>
     */
    long getRegisterTime();

    /**
     * <code>int64 lastLoginTime = 9;</code>
     */
    long getLastLoginTime();
  }
  /**
   * Protobuf type {@code proto.UserInfoData}
   */
  public  static final class UserInfoData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.UserInfoData)
      UserInfoDataOrBuilder {
    // Use UserInfoData.newBuilder() to construct.
    private UserInfoData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserInfoData() {
      uid_ = 0L;
      sessionKey_ = "";
      userAccout_ = "";
      name_ = "";
      sex_ = "";
      age_ = 0;
      status_ = 0;
      registerTime_ = 0L;
      lastLoginTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserInfoData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              uid_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sessionKey_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userAccout_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              sex_ = s;
              break;
            }
            case 48: {

              age_ = input.readInt32();
              break;
            }
            case 56: {

              status_ = input.readInt32();
              break;
            }
            case 64: {

              registerTime_ = input.readInt64();
              break;
            }
            case 72: {

              lastLoginTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.insping.libra.net.proto.ResUserInfo.internal_static_proto_UserInfoData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.insping.libra.net.proto.ResUserInfo.internal_static_proto_UserInfoData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.insping.libra.net.proto.ResUserInfo.UserInfoData.class, com.insping.libra.net.proto.ResUserInfo.UserInfoData.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <code>int64 uid = 1;</code>
     */
    public long getUid() {
      return uid_;
    }

    public static final int SESSIONKEY_FIELD_NUMBER = 2;
    private volatile java.lang.Object sessionKey_;
    /**
     * <code>string sessionKey = 2;</code>
     */
    public java.lang.String getSessionKey() {
      java.lang.Object ref = sessionKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionKey_ = s;
        return s;
      }
    }
    /**
     * <code>string sessionKey = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSessionKeyBytes() {
      java.lang.Object ref = sessionKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERACCOUT_FIELD_NUMBER = 3;
    private volatile java.lang.Object userAccout_;
    /**
     * <code>string userAccout = 3;</code>
     */
    public java.lang.String getUserAccout() {
      java.lang.Object ref = userAccout_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userAccout_ = s;
        return s;
      }
    }
    /**
     * <code>string userAccout = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserAccoutBytes() {
      java.lang.Object ref = userAccout_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAccout_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 4;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 5;
    private volatile java.lang.Object sex_;
    /**
     * <code>string sex = 5;</code>
     */
    public java.lang.String getSex() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sex_ = s;
        return s;
      }
    }
    /**
     * <code>string sex = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSexBytes() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 6;
    private int age_;
    /**
     * <code>int32 age = 6;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int STATUS_FIELD_NUMBER = 7;
    private int status_;
    /**
     * <code>int32 status = 7;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int REGISTERTIME_FIELD_NUMBER = 8;
    private long registerTime_;
    /**
     * <code>int64 registerTime = 8;</code>
     */
    public long getRegisterTime() {
      return registerTime_;
    }

    public static final int LASTLOGINTIME_FIELD_NUMBER = 9;
    private long lastLoginTime_;
    /**
     * <code>int64 lastLoginTime = 9;</code>
     */
    public long getLastLoginTime() {
      return lastLoginTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0L) {
        output.writeInt64(1, uid_);
      }
      if (!getSessionKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sessionKey_);
      }
      if (!getUserAccoutBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userAccout_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
      }
      if (!getSexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sex_);
      }
      if (age_ != 0) {
        output.writeInt32(6, age_);
      }
      if (status_ != 0) {
        output.writeInt32(7, status_);
      }
      if (registerTime_ != 0L) {
        output.writeInt64(8, registerTime_);
      }
      if (lastLoginTime_ != 0L) {
        output.writeInt64(9, lastLoginTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      if (!getSessionKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sessionKey_);
      }
      if (!getUserAccoutBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userAccout_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
      }
      if (!getSexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, sex_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, age_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, status_);
      }
      if (registerTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, registerTime_);
      }
      if (lastLoginTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, lastLoginTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.insping.libra.net.proto.ResUserInfo.UserInfoData)) {
        return super.equals(obj);
      }
      com.insping.libra.net.proto.ResUserInfo.UserInfoData other = (com.insping.libra.net.proto.ResUserInfo.UserInfoData) obj;

      boolean result = true;
      result = result && (getUid()
          == other.getUid());
      result = result && getSessionKey()
          .equals(other.getSessionKey());
      result = result && getUserAccout()
          .equals(other.getUserAccout());
      result = result && getName()
          .equals(other.getName());
      result = result && getSex()
          .equals(other.getSex());
      result = result && (getAge()
          == other.getAge());
      result = result && (getStatus()
          == other.getStatus());
      result = result && (getRegisterTime()
          == other.getRegisterTime());
      result = result && (getLastLoginTime()
          == other.getLastLoginTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUid());
      hash = (37 * hash) + SESSIONKEY_FIELD_NUMBER;
      hash = (53 * hash) + getSessionKey().hashCode();
      hash = (37 * hash) + USERACCOUT_FIELD_NUMBER;
      hash = (53 * hash) + getUserAccout().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + getSex().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + REGISTERTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRegisterTime());
      hash = (37 * hash) + LASTLOGINTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastLoginTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.insping.libra.net.proto.ResUserInfo.UserInfoData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.insping.libra.net.proto.ResUserInfo.UserInfoData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.insping.libra.net.proto.ResUserInfo.UserInfoData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.insping.libra.net.proto.ResUserInfo.UserInfoData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.insping.libra.net.proto.ResUserInfo.UserInfoData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.insping.libra.net.proto.ResUserInfo.UserInfoData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.insping.libra.net.proto.ResUserInfo.UserInfoData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.insping.libra.net.proto.ResUserInfo.UserInfoData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.insping.libra.net.proto.ResUserInfo.UserInfoData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.insping.libra.net.proto.ResUserInfo.UserInfoData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.insping.libra.net.proto.ResUserInfo.UserInfoData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.insping.libra.net.proto.ResUserInfo.UserInfoData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.insping.libra.net.proto.ResUserInfo.UserInfoData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.UserInfoData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.UserInfoData)
        com.insping.libra.net.proto.ResUserInfo.UserInfoDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.insping.libra.net.proto.ResUserInfo.internal_static_proto_UserInfoData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.insping.libra.net.proto.ResUserInfo.internal_static_proto_UserInfoData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.insping.libra.net.proto.ResUserInfo.UserInfoData.class, com.insping.libra.net.proto.ResUserInfo.UserInfoData.Builder.class);
      }

      // Construct using com.insping.libra.net.proto.ResUserInfo.UserInfoData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = 0L;

        sessionKey_ = "";

        userAccout_ = "";

        name_ = "";

        sex_ = "";

        age_ = 0;

        status_ = 0;

        registerTime_ = 0L;

        lastLoginTime_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.insping.libra.net.proto.ResUserInfo.internal_static_proto_UserInfoData_descriptor;
      }

      public com.insping.libra.net.proto.ResUserInfo.UserInfoData getDefaultInstanceForType() {
        return com.insping.libra.net.proto.ResUserInfo.UserInfoData.getDefaultInstance();
      }

      public com.insping.libra.net.proto.ResUserInfo.UserInfoData build() {
        com.insping.libra.net.proto.ResUserInfo.UserInfoData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.insping.libra.net.proto.ResUserInfo.UserInfoData buildPartial() {
        com.insping.libra.net.proto.ResUserInfo.UserInfoData result = new com.insping.libra.net.proto.ResUserInfo.UserInfoData(this);
        result.uid_ = uid_;
        result.sessionKey_ = sessionKey_;
        result.userAccout_ = userAccout_;
        result.name_ = name_;
        result.sex_ = sex_;
        result.age_ = age_;
        result.status_ = status_;
        result.registerTime_ = registerTime_;
        result.lastLoginTime_ = lastLoginTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.insping.libra.net.proto.ResUserInfo.UserInfoData) {
          return mergeFrom((com.insping.libra.net.proto.ResUserInfo.UserInfoData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.insping.libra.net.proto.ResUserInfo.UserInfoData other) {
        if (other == com.insping.libra.net.proto.ResUserInfo.UserInfoData.getDefaultInstance()) return this;
        if (other.getUid() != 0L) {
          setUid(other.getUid());
        }
        if (!other.getSessionKey().isEmpty()) {
          sessionKey_ = other.sessionKey_;
          onChanged();
        }
        if (!other.getUserAccout().isEmpty()) {
          userAccout_ = other.userAccout_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getSex().isEmpty()) {
          sex_ = other.sex_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (other.getRegisterTime() != 0L) {
          setRegisterTime(other.getRegisterTime());
        }
        if (other.getLastLoginTime() != 0L) {
          setLastLoginTime(other.getLastLoginTime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.insping.libra.net.proto.ResUserInfo.UserInfoData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.insping.libra.net.proto.ResUserInfo.UserInfoData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long uid_ ;
      /**
       * <code>int64 uid = 1;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>int64 uid = 1;</code>
       */
      public Builder setUid(long value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object sessionKey_ = "";
      /**
       * <code>string sessionKey = 2;</code>
       */
      public java.lang.String getSessionKey() {
        java.lang.Object ref = sessionKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sessionKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sessionKey = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSessionKeyBytes() {
        java.lang.Object ref = sessionKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sessionKey = 2;</code>
       */
      public Builder setSessionKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sessionKey = 2;</code>
       */
      public Builder clearSessionKey() {
        
        sessionKey_ = getDefaultInstance().getSessionKey();
        onChanged();
        return this;
      }
      /**
       * <code>string sessionKey = 2;</code>
       */
      public Builder setSessionKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userAccout_ = "";
      /**
       * <code>string userAccout = 3;</code>
       */
      public java.lang.String getUserAccout() {
        java.lang.Object ref = userAccout_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userAccout_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userAccout = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserAccoutBytes() {
        java.lang.Object ref = userAccout_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userAccout_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userAccout = 3;</code>
       */
      public Builder setUserAccout(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userAccout_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userAccout = 3;</code>
       */
      public Builder clearUserAccout() {
        
        userAccout_ = getDefaultInstance().getUserAccout();
        onChanged();
        return this;
      }
      /**
       * <code>string userAccout = 3;</code>
       */
      public Builder setUserAccoutBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userAccout_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 4;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sex_ = "";
      /**
       * <code>string sex = 5;</code>
       */
      public java.lang.String getSex() {
        java.lang.Object ref = sex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sex_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sex = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSexBytes() {
        java.lang.Object ref = sex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sex = 5;</code>
       */
      public Builder setSex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sex = 5;</code>
       */
      public Builder clearSex() {
        
        sex_ = getDefaultInstance().getSex();
        onChanged();
        return this;
      }
      /**
       * <code>string sex = 5;</code>
       */
      public Builder setSexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sex_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 6;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 6;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 6;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 7;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 7;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 7;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private long registerTime_ ;
      /**
       * <code>int64 registerTime = 8;</code>
       */
      public long getRegisterTime() {
        return registerTime_;
      }
      /**
       * <code>int64 registerTime = 8;</code>
       */
      public Builder setRegisterTime(long value) {
        
        registerTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 registerTime = 8;</code>
       */
      public Builder clearRegisterTime() {
        
        registerTime_ = 0L;
        onChanged();
        return this;
      }

      private long lastLoginTime_ ;
      /**
       * <code>int64 lastLoginTime = 9;</code>
       */
      public long getLastLoginTime() {
        return lastLoginTime_;
      }
      /**
       * <code>int64 lastLoginTime = 9;</code>
       */
      public Builder setLastLoginTime(long value) {
        
        lastLoginTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 lastLoginTime = 9;</code>
       */
      public Builder clearLastLoginTime() {
        
        lastLoginTime_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.UserInfoData)
    }

    // @@protoc_insertion_point(class_scope:proto.UserInfoData)
    private static final com.insping.libra.net.proto.ResUserInfo.UserInfoData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.insping.libra.net.proto.ResUserInfo.UserInfoData();
    }

    public static com.insping.libra.net.proto.ResUserInfo.UserInfoData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserInfoData>
        PARSER = new com.google.protobuf.AbstractParser<UserInfoData>() {
      public UserInfoData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserInfoData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserInfoData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfoData> getParserForType() {
      return PARSER;
    }

    public com.insping.libra.net.proto.ResUserInfo.UserInfoData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UserInfoData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UserInfoData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037protos/libra_res_userinfo.proto\022\005proto" +
      "\"\250\001\n\014UserInfoData\022\013\n\003uid\030\001 \001(\003\022\022\n\nsessio" +
      "nKey\030\002 \001(\t\022\022\n\nuserAccout\030\003 \001(\t\022\014\n\004name\030\004" +
      " \001(\t\022\013\n\003sex\030\005 \001(\t\022\013\n\003age\030\006 \001(\005\022\016\n\006status" +
      "\030\007 \001(\005\022\024\n\014registerTime\030\010 \001(\003\022\025\n\rlastLogi" +
      "nTime\030\t \001(\003B>\n\033com.insping.libra.net.pro" +
      "toB\013ResUserInfo\252\002\021LibraClient.protob\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_UserInfoData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_UserInfoData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UserInfoData_descriptor,
        new java.lang.String[] { "Uid", "SessionKey", "UserAccout", "Name", "Sex", "Age", "Status", "RegisterTime", "LastLoginTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
